{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.minio.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: minio-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.minio.namespaces }}
        principals: {{ .Values.istio.hardened.minio.principals }}
{{- end }}
